# -*- coding: utf-8 -*-
"""main file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Af3yiVNAre01LHdBkT6W6TcgTZYLak9
"""

def accept_text(text):
  text = text.lower()
  a = text.split()
  a.sort(reverse=False)
  for text in a:
    print(text)
    print('\n')
    
    
    
#test
b = accept_text("In typography, line length is the width of a block of typeset text, usually measured in units of length like inches or points or in characters per line in which case it is a measure. A block of text or paragraph has a maximum line length that fits a determined design. If the lines are too short then the text becomes disjointed; if they are too long the content loses rhythm as the reader searches for the start of each line")
print(b)

